# Generated by Django 5.1.15 on 2026-07-03 19:07

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crime_type', models.CharField(choices=[('theft', 'Theft'), ('robbery', 'Robbery'), ('assault', 'Assault'), ('homicide', 'Homicide'), ('drug_offense', 'Drug Offense'), ('weapons_offense', 'Weapons Offense'), ('fraud', 'Fraud'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('date_committed', models.DateField(blank=True, null=True)),
                ('case_number', models.CharField(blank=True, help_text='FIR / case reference number.', max_length=80)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('offender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crimes', to='offenders.offender')),
            ],
            options={
                'ordering': ['-date_committed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCrime',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('crime_type', models.CharField(choices=[('theft', 'Theft'), ('robbery', 'Robbery'), ('assault', 'Assault'), ('homicide', 'Homicide'), ('drug_offense', 'Drug Offense'), ('weapons_offense', 'Weapons Offense'), ('fraud', 'Fraud'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('date_committed', models.DateField(blank=True, null=True)),
                ('case_number', models.CharField(blank=True, help_text='FIR / case reference number.', max_length=80)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('added_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('offender', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='offenders.offender')),
            ],
            options={
                'verbose_name': 'historical crime',
                'verbose_name_plural': 'historical crimes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInventoryItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('item_type', models.CharField(choices=[('weapon', 'Weapon'), ('substance', 'Substance / Narcotic'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.CharField(blank=True, help_text="e.g. '1 unit', '250g'.", max_length=50)),
                ('storage_location', models.CharField(help_text="Where it's currently stored, e.g. station malkhana + rack ref.", max_length=255)),
                ('status', models.CharField(choices=[('in_custody', 'In Custody'), ('released', 'Released'), ('destroyed', 'Destroyed')], default='in_custody', max_length=20)),
                ('date_seized', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('added_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('crime', models.ForeignKey(blank=True, db_constraint=False, help_text='Optional - the specific crime this item was seized during.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='criminal_records.crime')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('offender', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='offenders.offender')),
            ],
            options={
                'verbose_name': 'historical inventory item',
                'verbose_name_plural': 'historical inventory items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('weapon', 'Weapon'), ('substance', 'Substance / Narcotic'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.CharField(blank=True, help_text="e.g. '1 unit', '250g'.", max_length=50)),
                ('storage_location', models.CharField(help_text="Where it's currently stored, e.g. station malkhana + rack ref.", max_length=255)),
                ('status', models.CharField(choices=[('in_custody', 'In Custody'), ('released', 'Released'), ('destroyed', 'Destroyed')], default='in_custody', max_length=20)),
                ('date_seized', models.DateField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('crime', models.ForeignKey(blank=True, help_text='Optional - the specific crime this item was seized during.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='criminal_records.crime')),
                ('offender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='offenders.offender')),
            ],
            options={
                'ordering': ['-date_seized', '-created_at'],
            },
        ),
    ]
