# Generated by Django 5.1.15 on 2026-07-03 19:07

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOffender',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=150)),
                ('aliases', models.CharField(blank=True, help_text='Comma-separated known aliases.', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20)),
                ('present_address', models.TextField(blank=True)),
                ('date_of_last_arrest', models.DateField(blank=True, null=True)),
                ('latitude', models.FloatField(help_text='Registered address latitude.')),
                ('longitude', models.FloatField(help_text='Registered address longitude.')),
                ('offender_image', models.TextField(blank=True, max_length=100, null=True)),
                ('parole_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('absconded', 'Absconded')], default='active', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', help_text="Cached, auto-recalculated from the offender's crime count.", max_length=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('district', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geography.district')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('police_station', models.ForeignKey(blank=True, db_constraint=False, help_text='Home / registering police station.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geography.policestation')),
                ('ps_arrested', models.ForeignKey(blank=True, db_constraint=False, help_text='Police station where the offender was arrested, if different.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geography.policestation')),
            ],
            options={
                'verbose_name': 'historical offender',
                'verbose_name_plural': 'historical offenders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Offender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('aliases', models.CharField(blank=True, help_text='Comma-separated known aliases.', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20)),
                ('present_address', models.TextField(blank=True)),
                ('date_of_last_arrest', models.DateField(blank=True, null=True)),
                ('latitude', models.FloatField(help_text='Registered address latitude.')),
                ('longitude', models.FloatField(help_text='Registered address longitude.')),
                ('offender_image', models.ImageField(blank=True, null=True, upload_to='offenders/photos/')),
                ('parole_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('absconded', 'Absconded')], default='active', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', help_text="Cached, auto-recalculated from the offender's crime count.", max_length=10)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offenders', to='geography.district')),
                ('police_station', models.ForeignKey(help_text='Home / registering police station.', on_delete=django.db.models.deletion.PROTECT, related_name='registered_offenders', to='geography.policestation')),
                ('ps_arrested', models.ForeignKey(blank=True, help_text='Police station where the offender was arrested, if different.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrested_offenders', to='geography.policestation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
